In [1]:
import pandas as pd

In [2]:
## Concatenatn Merge and Join Operations in Pandas

In [9]:
data ={'name':['sudh','krish','hitesh','tulesko'],
       'salary':[100, 200, 300, 400],
        'maild' :['sudh@ineuron.ai','krish@ineuron.ai','hitesh@ineuron.ai','tulesko@ineuron.ai'],
       'addr':['blr', 'blr', 'blr', 'mum']
}

In [18]:
pd.DataFrame(data)

name  salary               maild addr
0     sudh     100     sudh@ineuron.ai  blr
1    krish     200    krish@ineuron.ai  blr
2   hitesh     300   hitesh@ineuron.ai  blr
3  tulesko     400  tulesko@ineuron.ai  mum

In [6]:
## Keys will become columns and values will become rows
## using DataFrame() function we can convert to dataframe

In [42]:
pd.DataFrame(data)

name  salary               maild addr
0     sudh     100     sudh@ineuron.ai  blr
1    krish     200    krish@ineuron.ai  blr
2   hitesh     300   hitesh@ineuron.ai  blr
3  tulesko     400  tulesko@ineuron.ai  mum

In [29]:
df=pd.DataFrame(data,index=[4,5,6,7])
df

name  salary               maild addr
4     sudh     100     sudh@ineuron.ai  blr
5    krish     200    krish@ineuron.ai  blr
6   hitesh     300   hitesh@ineuron.ai  blr
7  tulesko     400  tulesko@ineuron.ai  mum

In [25]:
df.loc[5:6] ##Named indexes ie on screen

name  salary              maild addr
5   krish     200   krish@ineuron.ai  blr
6  hitesh     300  hitesh@ineuron.ai  blr

In [28]:
df.iloc[5:6] ## iloc default indexes not on screen

Empty DataFrame
Columns: [name, salary, maild, addr]
Index: []

In [33]:
df.iloc[2:4]

name  salary               maild addr
6   hitesh     300   hitesh@ineuron.ai  blr
7  tulesko     400  tulesko@ineuron.ai  mum

In [34]:
## String based indexes for rows

In [35]:
df=pd.DataFrame(data,index=['sudh','krish','hitesh','tulesko'])

In [36]:
df

name  salary               maild addr
sudh        sudh     100     sudh@ineuron.ai  blr
krish      krish     200    krish@ineuron.ai  blr
hitesh    hitesh     300   hitesh@ineuron.ai  blr
tulesko  tulesko     400  tulesko@ineuron.ai  mum

In [41]:
df.loc['sudh':'hitesh']

name  salary              maild addr
sudh      sudh     100    sudh@ineuron.ai  blr
krish    krish     200   krish@ineuron.ai  blr
hitesh  hitesh     300  hitesh@ineuron.ai  blr

In [44]:
df=pd.DataFrame(data)

In [45]:
df

name  salary               maild addr
0     sudh     100     sudh@ineuron.ai  blr
1    krish     200    krish@ineuron.ai  blr
2   hitesh     300   hitesh@ineuron.ai  blr
3  tulesko     400  tulesko@ineuron.ai  mum

In [46]:
df.iloc[1:3]

name  salary              maild addr
1   krish     200   krish@ineuron.ai  blr
2  hitesh     300  hitesh@ineuron.ai  blr

In [47]:
data1= {'pf_nu' : [234,45,54465,656],
        'income_tax' : [234,565,767,6778],
        'mobile_no' : [23543,43543,454,5656],
        'courses' : ['ds' , 'bigdata' , 'web dev ' , 'blockchian']
    
}

In [48]:
df1=pd.DataFrame(data1)

In [49]:
df1

pf_nu  income_tax  mobile_no     courses
0    234         234      23543          ds
1     45         565      43543     bigdata
2  54465         767        454    web dev 
3    656        6778       5656  blockchian

In [50]:
df

name  salary               maild addr
0     sudh     100     sudh@ineuron.ai  blr
1    krish     200    krish@ineuron.ai  blr
2   hitesh     300   hitesh@ineuron.ai  blr
3  tulesko     400  tulesko@ineuron.ai  mum

In [52]:
## Concatenation 
## Merge can be horizontal as well as vertical
## Data1<->Data2 Side by side
## Data1
## Data2 One above other

In [53]:
pd.concat([df,df1]) ## By default its concats vertically one below other
## aix=0 by default


name  salary               maild addr    pf_nu  income_tax  mobile_no  \
0     sudh   100.0     sudh@ineuron.ai  blr      NaN         NaN        NaN   
1    krish   200.0    krish@ineuron.ai  blr      NaN         NaN        NaN   
2   hitesh   300.0   hitesh@ineuron.ai  blr      NaN         NaN        NaN   
3  tulesko   400.0  tulesko@ineuron.ai  mum      NaN         NaN        NaN   
0      NaN     NaN                 NaN  NaN    234.0       234.0    23543.0   
1      NaN     NaN                 NaN  NaN     45.0       565.0    43543.0   
2      NaN     NaN                 NaN  NaN  54465.0       767.0      454.0   
3      NaN     NaN                 NaN  NaN    656.0      6778.0     5656.0   

      courses  
0         NaN  
1         NaN  
2         NaN  
3         NaN  
0          ds  
1     bigdata  
2    web dev   
3  blockchian

In [54]:
pd.concat([df,df1],axis=1) ## Rows wise concatenation axis=1

name  salary               maild addr  pf_nu  income_tax  mobile_no  \
0     sudh     100     sudh@ineuron.ai  blr    234         234      23543   
1    krish     200    krish@ineuron.ai  blr     45         565      43543   
2   hitesh     300   hitesh@ineuron.ai  blr  54465         767        454   
3  tulesko     400  tulesko@ineuron.ai  mum    656        6778       5656   

      courses  
0          ds  
1     bigdata  
2    web dev   
3  blockchian

In [57]:
data2 ={'0':['sudh','krish','hitesh','tulesko'],
       '1':[100, 200, 300, 400],
        '2' :['sudh@ineuron.ai','krish@ineuron.ai','hitesh@ineuron.ai','tulesko@ineuron.ai'],
       '3':['blr', 'blr', 'blr', 'mum']
}

In [58]:
data3= {'0' : [234,45,54465,656],
        '1' : [234,565,767,6778],
        '2' : [23543,43543,454,5656],
        '3' : ['ds' , 'bigdata' , 'web dev ' , 'blockchian']
    
}

In [59]:
df2=pd.DataFrame(data2)

In [60]:
df3=pd.DataFrame(data3)

In [61]:
df2

0    1                   2    3
0     sudh  100     sudh@ineuron.ai  blr
1    krish  200    krish@ineuron.ai  blr
2   hitesh  300   hitesh@ineuron.ai  blr
3  tulesko  400  tulesko@ineuron.ai  mum

In [62]:
df3

0     1      2           3
0    234   234  23543          ds
1     45   565  43543     bigdata
2  54465   767    454    web dev 
3    656  6778   5656  blockchian

In [63]:
pd.concat([df2,df3])

0     1                   2           3
0     sudh   100     sudh@ineuron.ai         blr
1    krish   200    krish@ineuron.ai         blr
2   hitesh   300   hitesh@ineuron.ai         blr
3  tulesko   400  tulesko@ineuron.ai         mum
0      234   234               23543          ds
1       45   565               43543     bigdata
2    54465   767                 454    web dev 
3      656  6778                5656  blockchian

In [65]:
## For complete vertical merge column and row names must be similar as above 
## Else NAN values will be there
## If column name is same, then NAN values will not come and it will show complete vertical concat operation

In [77]:
data4={
    'emp_id': [101,102,103,104],
    'salary': [234,345,200,400],
    'pf': [23,34,56,78]
    
}

In [78]:
data5={
    'emp_id': [101,102,104,105],
    'mob_no': [3434,5656,767,878],
    'house_nu': [345,345,345,56]
    
}

In [79]:
df4=pd.DataFrame(data4)
df4

emp_id  salary  pf
0     101     234  23
1     102     345  34
2     103     200  56
3     104     400  78

In [80]:
df5=pd.DataFrame(data5)
df5

emp_id  mob_no  house_nu
0     101    3434       345
1     102    5656       345
2     104     767       345
3     105     878        56

In [81]:
pd.merge(df4,df5)

emp_id  salary  pf  mob_no  house_nu
0     101     234  23    3434       345
1     102     345  34    5656       345
2     104     400  78     767       345

In [82]:
## By default it will perform inner merge takes all the common values in merged table

In [85]:
pd.merge(df4,df5,how='left')
## merge(leftdf, rightdf, how)

emp_id  salary  pf  mob_no  house_nu
0     101     234  23  3434.0     345.0
1     102     345  34  5656.0     345.0
2     103     200  56     NaN       NaN
3     104     400  78   767.0     345.0

In [86]:
pd.merge(df4,df5,how='right')

emp_id  salary    pf  mob_no  house_nu
0     101   234.0  23.0    3434       345
1     102   345.0  34.0    5656       345
2     104   400.0  78.0     767       345
3     105     NaN   NaN     878        56

In [87]:
## Missing values will be filled by NaN

In [88]:
pd.merge(df4,df5,how='right',on="emp_id")

emp_id  salary    pf  mob_no  house_nu
0     101   234.0  23.0    3434       345
1     102   345.0  34.0    5656       345
2     104   400.0  78.0     767       345
3     105     NaN   NaN     878        56

In [89]:
data6={
    'emp_id1': [101,102,103,104],
    'salary': [234,345,200,400],
    'pf': [23,34,56,78]
    
}

data7={
    'emp_id2': [101,102,104,105],
    'mob_no': [3434,5656,767,878],
    'house_nu': [345,345,345,56]
    
}

In [91]:
df6=pd.DataFrame(data6)

In [92]:
df7=pd.DataFrame(data7)

In [93]:
df6

emp_id1  salary  pf
0      101     234  23
1      102     345  34
2      103     200  56
3      104     400  78

In [94]:
df7

emp_id2  mob_no  house_nu
0      101    3434       345
1      102    5656       345
2      104     767       345
3      105     878        56

If no common columns then we can specify lefton and right on to comsider as similar

In [98]:
pd.merge(df6,df7,left_on='emp_id1',right_on='emp_id2')

emp_id1  salary  pf  emp_id2  mob_no  house_nu
0      101     234  23      101    3434       345
1      102     345  34      102    5656       345
2      104     400  78      104     767       345

In [99]:
pd.merge(df6,df7,left_on='emp_id1',right_on='emp_id2',how='inner')

emp_id1  salary  pf  emp_id2  mob_no  house_nu
0      101     234  23      101    3434       345
1      102     345  34      102    5656       345
2      104     400  78      104     767       345

In [102]:
data8 = {'emp_id' : [101,102,103,104],
         'salary' : [234, 345,200,400],
         'pf' : [23,34,56,78],
         }
         
data9  = {'emp_id' : [101,102,104,105],
          'salary' : [234, 345,200,878],
          'house_nu' : [345,345,345,56]
    
}

In [103]:
df8=pd.DataFrame(data8)
df9=pd.DataFrame(data9)

In [104]:
df8

emp_id  salary  pf
0     101     234  23
1     102     345  34
2     103     200  56
3     104     400  78

In [105]:
df9

emp_id  salary  house_nu
0     101     234       345
1     102     345       345
2     104     200       345
3     105     878        56

In [106]:
pd.merge(df8,df9,on=['emp_id','salary'])

emp_id  salary  pf  house_nu
0     101     234  23       345
1     102     345  34       345

In [107]:
## Dimension Difference

In [109]:
data8 = {'emp_id' : [101,102,103,104],
         'salary' : [234, 345,200,400],
         'pf' : [23,34,56,78],
         }
         
data9  = {'emp_id' : [101,102,104,105,106],
          'salary' : [234, 345,200,878,898],
          'house_nu' : [345,345,345,56,67]
    
}

df8=pd.DataFrame(data8)
df9=pd.DataFrame(data9)

In [111]:
df8

emp_id  salary  pf
0     101     234  23
1     102     345  34
2     103     200  56
3     104     400  78

In [112]:
df9

emp_id  salary  house_nu
0     101     234       345
1     102     345       345
2     104     200       345
3     105     878        56
4     106     898        67

In [113]:
pd.merge(df8,df9,on=['emp_id','salary'])

emp_id  salary  pf  house_nu
0     101     234  23       345
1     102     345  34       345

In [114]:
## New Topic

In [130]:
data10 = {'emp_id1' : [101,102,103,104],
         'salary1' : [234, 345,200,400],
         'pf' : [23,34,56,78],
         }
         
data11  = {'emp_id2' : [101,102,104,105,123],
          'salary2' : [234, 345,200,878,43],
          'house_nu' : [345,345,345,56,234]
    
}

df10=pd.DataFrame(data10,index=['a','b','c','d'])
df11=pd.DataFrame(data11,index=['a','b','d','e','f'])

In [131]:
df10


emp_id1  salary1  pf
a      101      234  23
b      102      345  34
c      103      200  56
d      104      400  78

In [133]:
df11

emp_id2  salary2  house_nu
a      101      234       345
b      102      345       345
d      104      200       345
e      105      878        56
f      123       43       234

In [134]:
df10.join(df11) # Match basis row indexes

emp_id1  salary1  pf  emp_id2  salary2  house_nu
a      101      234  23    101.0    234.0     345.0
b      102      345  34    102.0    345.0     345.0
c      103      200  56      NaN      NaN       NaN
d      104      400  78    104.0    200.0     345.0

In [135]:
## Merge uses Column names to join pd.merge(df,df1)
## Join uses row Indexes to join df.join(df1)

In [139]:
df_sales=pd.read_csv("sales_data_final.csv")

In [141]:
df_sales.head(2)

order_id order_date ship_date       ship_mode    customer_name  \
0   AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1  IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

    segment            state    country  market   region  ...  \
0  Consumer      Constantine    Algeria  Africa   Africa  ...   
1  Consumer  New South Wales  Australia    APAC  Oceania  ...   

          category sub_category              product_name sales quantity  \
0  Office Supplies      Storage       Tenex Lockers, Blue   408        2   
1  Office Supplies     Supplies  Acme Trimmer, High Speed   120        3   

   discount   profit  shipping_cost  order_priority  year  
0       0.0  106.140          35.46          Medium  2011  
1       0.1   36.036           9.72          Medium  2011  

[2 rows x 21 columns]

In [147]:
def profit_flag(a):
    if a>=0:
        return 'Positive'
    else:
        return 'Negative'

In [148]:
 profit_flag(67)


'Positive'

In [149]:
 profit_flag(-4)

'Negative'

In [150]:
df_sales['flag_profit']=df_sales['profit'].apply(profit_flag)

In [152]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ... sub_category  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...      Storage   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...     Supplies   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...      Storage   
3  Home Office        Stockholm     Sweden      EU    North  ...        Paper   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...  Furnishings   

                  product_name sales quantity discount   profit  \
0          Tenex Lockers, Blue   408        2      0.0  106.140   
1     Acme Trimmer, High Speed   120        3      0.1   36.036   
2      Tenex Box, Single Width    66        4      0.0   29.640   
3  Enermax Note Cards, Premium    45        3      0.5  -26.055   
4   Eldon Light Bulb, Duo Pack   114        5      0.1   37.770   

   shipping_cost  order_priority  year flag_profit  
0          35.46          Medium  2011    Positive  
1           9.72          Medium  2011    Positive  
2           8.17            High  2011    Positive  
3           4.82            High  2011    Negative  
4           4.70          Medium  2011    Positive  

[5 rows x 22 columns]

In [153]:
def lenght_name(name):
    return len(name)


In [155]:
df_sales['Len_CustomerName']=df_sales['customer_name'].apply(len)

In [157]:
df_sales.head(2)

order_id order_date ship_date       ship_mode    customer_name  \
0   AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1  IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

    segment            state    country  market   region  ...  \
0  Consumer      Constantine    Algeria  Africa   Africa  ...   
1  Consumer  New South Wales  Australia    APAC  Oceania  ...   

               product_name sales quantity discount   profit  shipping_cost  \
0       Tenex Lockers, Blue   408        2      0.0  106.140          35.46   
1  Acme Trimmer, High Speed   120        3      0.1   36.036           9.72   

   order_priority  year  flag_profit Len_CustomerName  
0          Medium  2011     Positive               15  
1          Medium  2011     Positive               11  

[2 rows x 23 columns]

In [158]:
## Quantity Flag

In [160]:
def quantity_flag(a):
    if a<10:
        return 'Low'
    elif a>10 and a<20:
        return 'Medium'
    else:
        return 'High'

In [162]:
df_sales['flag_quantity']=df_sales['quantity'].apply(quantity_flag)

In [163]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ... sales  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...   408   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...   120   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...    66   
3  Home Office        Stockholm     Sweden      EU    North  ...    45   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...   114   

  quantity discount   profit shipping_cost  order_priority  year  flag_profit  \
0        2      0.0  106.140         35.46          Medium  2011     Positive   
1        3      0.1   36.036          9.72          Medium  2011     Positive   
2        4      0.0   29.640          8.17            High  2011     Positive   
3        3      0.5  -26.055          4.82            High  2011     Negative   
4        5      0.1   37.770          4.70          Medium  2011     Positive   

   Len_CustomerName flag_quantity  
0                15           Low  
1                11           Low  
2                13           Low  
3                12           Low  
4                11           Low  

[5 rows x 24 columns]

In [164]:
df_sales['square_quantity']=df_sales['quantity'].apply(lambda x: x*x)

In [165]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ... quantity  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...        2   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...        3   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...        4   
3  Home Office        Stockholm     Sweden      EU    North  ...        3   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...        5   

  discount   profit shipping_cost order_priority  year  flag_profit  \
0      0.0  106.140         35.46         Medium  2011     Positive   
1      0.1   36.036          9.72         Medium  2011     Positive   
2      0.0   29.640          8.17           High  2011     Positive   
3      0.5  -26.055          4.82           High  2011     Negative   
4      0.1   37.770          4.70         Medium  2011     Positive   

   Len_CustomerName  flag_quantity square_quantity  
0                15            Low               4  
1                11            Low               9  
2                13            Low              16  
3                12            Low               9  
4                11            Low              25  

[5 rows x 25 columns]

# Numpy

In [166]:
import numpy as np

In [168]:
## EDA: Exploratory Data Analysis can be done using panadas numpy scikitlearn and so on

In [170]:
## Metlab is converted into python as numpy library for performing EDA

In [172]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [173]:
type(np.array([1,2,3,4,5]))

# N dimensional array numpy.ndarray

numpy.ndarray

In [174]:
np.array([[2,3,4],[5,6,7]])

array([[2, 3, 4],
       [5, 6, 7]])

In [175]:
type(np.array([[2,3,4],[5,6,7]]))

numpy.ndarray

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [177]:
l=[[1,2,3,4],[2,3,4,5]]

In [178]:
## Just as lists we can access arrays
l[0]

[1, 2, 3, 4]

In [180]:
l[0][0]

1

In [185]:
array=np.array([[1,2,3,4],[2,3,4,5]])

In [186]:
array[0][0]

1

In [189]:
array=np.array([1,2,3,4],ndmin=3)
## We can specify dimensions for array

In [188]:
array

array([[[1, 2, 3, 4]]])

In [190]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [193]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [196]:
arr.ndim

2

In [197]:
np.random.randint(1,10,(4,4))

array([[7, 2, 7, 4],
       [6, 7, 8, 1],
       [8, 3, 7, 9],
       [4, 2, 4, 8]])

In [198]:
np.random.randint(1,10,(4,4,2))

array([[[2, 6],
        [7, 4],
        [7, 4],
        [4, 2]],

       [[9, 1],
        [3, 8],
        [8, 8],
        [3, 1]],

       [[8, 3],
        [2, 9],
        [5, 4],
        [2, 5]],

       [[8, 2],
        [4, 3],
        [9, 9],
        [4, 4]]])

In [199]:
np.random.randint(1,10,(4,3,2))


array([[[7, 7],
        [1, 2],
        [4, 8]],

       [[4, 7],
        [4, 4],
        [9, 6]],

       [[9, 7],
        [6, 5],
        [8, 2]],

       [[7, 1],
        [6, 6],
        [2, 3]]])